version: '3.8'

services: 
  ros-wheelchair: 
    image: wheelchair-project-1
    build: 
      context: .
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - XDG_RUNTIME_DIR=/tmp/runtime-root
    volumes: 
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    devices: 
      - /dev/dri:/dev/dri
    stdin_open: true
    tty: true



