DWAPlannerROS:

  max_vel_x: 3.0
  min_vel_x: -1.5

  max_vel_trans: 3.0
  min_vel_trans: -1.5

  max_vel_theta: 2.0
  min_vel_theta: -2.0

  acc_lim_x: 2.5

  xy_goal_tolerance: 0.05
  yaw_goal_tolerance: 0.17
  latch_xy_goal_tolerance: false

  sim_time: 1.5
  vx_samples: 20
  vy_samples: 0
  vth_samples: 40
  controller_frequency: 10.0

  path_distance_bias: 32.0
  goal_distance_bias: 20.0
  occdist_scale: 0.02
  forward_point_distance: 0.325
  stop_time_buffer: 0.2
  scalling_speed: 0.25
  max_scalling_factor: 0.25

  oscilation_reset_dist: 0.05

  publish_traj_pc: true
  publish_cost_grid_pc: true

