scan_filter_chain:
- name: angle_filter_1
  type: laser_filters/LaserScanAngularBoundsFilterInPlace
  params:
    lower_angle: -3.15
    upper_angle: -1.3
- name: angle_filter_2
  type: laser_filters/LaserScanAngularBoundsFilterInPlace
  params:
    lower_angle: 1.3
    upper_angle: 3.15