ROBOT_FRAME: "base_link"
MAX_VELOCITY: 2.0
MIN_VELOCITY: 0.0
MAX_YAWRATE: 2.0
MIN_YAWRATE: 0.0
MAX_IN_PLACE_YAWRATE: 1.5
MIN_IN_PLACE_YAWRATE: 0.05
MAX_ACCELERATION: 4.0
MAX_DECELERATION: 3.0
MAX_D_YAWRATE: 3.2